site_name: nfipmultiloss
site_url: https://github.com/
markdown_extensions:
    - toc:
        baselevel: 2
nav:
    - Home: index.md
    - "Authentication with Google": authentication-google.md
    - "Subscription with Stripe": subscription-stripe.md
    - "Subscription with Buy Me A Coffee": subscription-buymeacoffee.md
    - "Contribute": contribute.md
