testing_mode = true
payment_provider = "stripe" 
stripe_api_key_test = "sk_test_51OUrkXGRrZrHyuzEsLd3DO9BlkDNDXkySFmsJ3iT0OJmd6lBab2w6Q8FCvLB0GMNiNTbwJlY5iLdiWnYBleGFpGG00QXFmxVnp" #only needed if using Stripe
stripe_api_key = "sk_test_51OUrkXGRrZrHyuzEsLd3DO9BlkDNDXkySFmsJ3iT0OJmd6lBab2w6Q8FCvLB0GMNiNTbwJlY5iLdiWnYBleGFpGG00QXFmxVnp" #only needed if using Stripe
stripe_link = "https://buy.stripe.com/test_9AQ5mB2Gq9KwdZ65kk" #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_9AQ5mB2Gq9KwdZ65kk" #only needed if using Stripe
client_id = "512085322197-ilpmadg75hkbsg0parvq7mf1jjih4bg9.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url ="https://nfipml.streamlit.app/"
